### ISSUE TITLE
Reporte de practica Architect

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/practica-architect-ArturoAngonJose#1]
[Reporte Architect.pdf](https://github.com/SistemasTecTlaxiaco/practica-architect-ArturoAngonJose/files/7158509/Reporte.Architect.pdf)

**Comment by IsaHuerta23** [comment]
Redacción y ortografía: 3pts.
Exposición de ideas centrales: 3pts.
Organización de la información: 3pts.
Uso de imágenes y colores: 1pto.
Presentación visual: 3pts.
Referencias: 0pts.
Presentación: 3pts.

Calificación: 16.

**Comment by IsaHuerta23** [comment]
Portada: 25 pts.
Procedimiento: 25 pts.
Figuras, ilustraciones y fotografías: 25 pts.
Resultados y conclusiones: 22 pts.

Total: 97 pts.
Calificación: 19.4.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
